---
title: "Assginment02"
author: "Zhen Liu"
date: "2022-10-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Data Wrangling 
### 1.1 Select and Filter 
#### Q1
```{r load-packages, include=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(tidyverse)
library(Stat2Data)
data("Hawks")
```


```{r}
hSF<-Hawks%>%
  filter(Species == 'RT'& Weight > 1)%>%
  select(Wing,Weight,Tail)
head(hSF)
```
#### Q2 
#### How many variables does the data frame hSF have? How mant examples does the data frame hSF have? How many observations? How many cases?

```{r}

dim(hSF)
```

totally 3 variables Wing, Weight, Tail\
totally 573 obervations per variable\
totally 1716 cases or examples

### 1.2 The arrange function

#### Q1

```{r}
head(hSF %>%  arrange((Wing)),5)

```
### 1.3 Join and rename functions 

#### Q1

```{r}
Species <- c("CH","RT","SS")
species_name_full <- c("Cooper's","Red-tailed","Sharp-shinned")
hawkSpeciesNameCodes<- data.frame(Species, species_name_full)
```

#### Q2
```{r}
hawksFullName <- left_join(Hawks,hawkSpeciesNameCodes,by = "Species")

hawksFullName<- (hawksFullName%>%select(-Species)%>%rename(Species =species_name_full ))

```
#### Q3
```{r}
head(hawksFullName%>%select(Species,Wing,Weight))
```
##

