---
title: "Assignment 05"
author: "Zhen Liu"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

## Conditional probability, Bayes rule and independence

### Bayes theorem 

#### Q1 

$$P(A) = 0.9\\
P(B|A) = 0.8\\
P(B^c|A^c) =0.75
$$
$$P(B) = P(B|A)*P(A) + P(B|A^c)*P(A^c)=P(B|A)*P(A) +[1-P(B^c|A^c)]*[1-P(A)] = 0.8*0.9+0.25*0.1 =0.745
$$
$$P(A|B) = \frac{P(A)*P(B|A)}{P(B)} = 0.9*0.8/0.745 = 0.966$$

### Conditional probabilities

#### Q1

1. $$P(A|B) = \frac{P(A\cap B)}{P(B)} \\
A\subseteq B\\
P(A\cap B)=P(A) \\
P(A|B) = \frac{P(A)}{P(B)}$$
$$P(A|B) =1$$
2. $$P(A|B) = 0 \\ P(A) = 0$$  
3. $$P(A|B) = \frac{P(A\cap B)}{P(B)} =\frac{P(B)}{P(B)} =1\\
P(B) = 0$$
4. $$P(A|Ω)) = \frac{P(A\capΩ)}{P(Ω)}\\
P(Ω) =1\\
P(A|Ω)) = P(A)$$
5. $$P(A\cap B\cap C) = P(A\cap (B\cap C)) = P(A|(B\cap C))P(B\cap C)\\ = P(A|(B\cap C))(P(B|C)P(C))\\=P(A|(B\cap C)*P(B|C)*P(C)$$
6.$$P(A|B\cap C) = \frac{P(A\cap B\cap C)}{P(B|C)*P(C)}\\
=\frac{P(B|A\cap C)*P(A|C)*P(C)}{P(B|C)*P(C)}\\=\frac{P(B|A\cap C)*P(A|C)}{P(B|C)}$$

#### Q2

$$P(A|B) = 0.3\\
P(A|B^c) = 0.1\\
P(B) = 0.2\\
P(A^c) = 1-P(A)\\
P(A) = P(A|B) *P(B) + P(A|B^c)*P(B^c) \\=
0.3*0.2 + 0.1*0.8 = 0.14\\
P(A^c) = 0.86$$

### Mutual independence and pair-wise independent
#### Q1 

$$A := \{(1,0,1),(1,1,0)\}, B := \{(0,1,1),(1,1,0)\} \\ C:=\{(0,1,1),(1,0,1)\}\\
P(A) = P(B) = P(C) =1/2\\
P(A\cap B) = P(A)*P(B) = 1/4\\
P(A\cap C) = P(A)*P(C) = 1/4\\
P(C\cap B) = P(C) *P(B) = 1/4\\
P(A\cap B\cap C) = 0$$
it is pariwise-independent 

### The Monty hall problem
#### Q1 (optional)

## Random variables and discrete random variables

### Expectation and variance 
#### Q1


$$Cov(X,Y) := E[(X-\overline{X})*(Y-\overline{Y})]\\
Cov(X,Y) := E(XY) - E(X)E(Y)\\
= E(X)E(Y) - E(X)E(Y) = 0$$


### Distributions

#### Q1

1. $$ P_X({x}) =   \left\{
\begin{array}{ll}
      \alpha & X=3 \\
      \beta & X =10 \\
      1-（\alpha + \beta） & X = 0 \\
      0 & otherwise
\end{array} 
\right.  $$

2. $$E(X):= \sum_{x\in\{0,3,10\}}x*p_X(x)=3\alpha +10\beta$$
3. $$Var(X) = E(X^2)-E(X)^2 = (9\alpha+100\beta)-(3\alpha+10\beta)^2$$
4. $$SD = \sqrt{Var(X)}$$

#### Q2

1. $$P_X(S)=(1-\alpha-\beta)1_S(0)+\alpha1_S(3)+\beta1_S(10)$$
2. 
    $$ F_X（x） =   \left\{
\begin{array}{ll}
      0 &x<0 \\
      1-（\alpha + \beta)&0<=x<3\\
      1 - \beta & 3<=x<10 \\
      1 & x>=10
\end{array} 
\right.  $$

#### Q3 

$$
Var(Y) = n*(E(X^2)-E(X)^2) = n*((9\alpha+100\beta)-(3\alpha+10\beta)^2)
$$


#### Q4


```{r}
rmultinom(2, 7, prob=c(0.5, 0.2, 0.3))
```

```{r}
a<-rmultinom(5, 3, prob=c(0.5, 0.2, 0.3))
b<-a[1,]*0+a[2,]*3+a[3,]*10
```


```{r}
c<-data.frame(b)
c
```


```{r}
samples_Xi<-rmultinom(50000, 3, prob=c(0.5, 0.2, 0.3))
```


```{r}
Y<-samples_Xi[1,]*0+samples_Xi[2,]*3+samples_Xi[3,]*10
samples_Y = data.frame(Y)
```


```{r}
ggplot(samples_Y,aes(Y))+geom_bar()
```
```{r}
samples_Xi_n<-rmultinom(50000, 20, prob=c(0.5, 0.2, 0.3))
```
```{r}
Y_n<-samples_Xi_n[1,]*0+samples_Xi_n[2,]*3+samples_Xi_n[3,]*10
samples_Y_n = data.frame(Y_n)
ggplot(samples_Y_n,aes(Y_n))+geom_bar()
```
maximum value is 2300, minumum value is 0, range is 0~150



```{r}
samples_Xi_t<-rmultinom(50000, 2000, prob=c(0.5, 0.2, 0.3))

Y_t<-samples_Xi_t[1,]*0+samples_Xi_t[2,]*3+samples_Xi_t[3,]*10

samples_Y_t = data.frame(Y_t)


ggplot(samples_Y_t,aes(Y_t))+geom_bar()

```
