---
title: "Assginment03"
author: "Zhen Liu"
date: "2022-10-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Exploratory data analysis




```{r}

library(tidyverse)
library(Stat2Data)
data("Hawks")
```

```{r}
head(Hawks)

```
### 1.1 Location estimators

#### Q1 

```{r}


HawksTail<-Hawks[['Tail']]

HawksTail
```
```{r}

class(HawksTail)

mean(HawksTail)


median(HawksTail)
```
### 1.2 Combining location estimators with the summarise function 
#### Q1

```{r}

hawksFullName%>%
  summarise(Wing_mean= mean(Wing,na.rm = TRUE),Wing_t_mean = mean(Wing,na.rm = TRUE,trim = 0.5), Wing_med = median(Wing,na.rm = TRUE),Weight_mean= mean(Weight,na.rm = TRUE),Weight_t_mean = mean(Weight,na.rm = TRUE,trim = 0.5), Weight_med = median(Weight,na.rm = TRUE))


```
#### Q2
```{r}


hawksFullName%>%
  group_by(Species)%>%
  summarise(Wing_mean= mean(Wing,na.rm = TRUE),Wing_t_mean = mean(Wing,na.rm = TRUE,trim = 0.5), Wing_med = median(Wing,na.rm = TRUE),Weight_mean= mean(Weight,na.rm = TRUE),Weight_t_mean = mean(Weight,na.rm = TRUE,trim = 0.5), Weight_med = median(Weight,na.rm = TRUE))



```

### 1.3 Location and dispersion estimators under linear transformations 

#### Q1

```{r}

a<- 2
b<-3

mean(HawksTail*a +b)

mean(HawksTail)

```
The mean of HawksTail*a +b is almost double times as HawksTail

#### Q2

```{r}






```

